title: James Mesich # your name (or website title) here
logo: "images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  James Mesich is an 
  <br><br>
  Languages: Python, Java, C++, Matlab, SQL
  Frameworks & Technologies: PyTorch, Google Cloud Platform, Numpy, Sci-kit learn, Flask, Django, Streamlit, Selenium
  
  <a href="https://www.linkedin.com/in/james-mesich/">View My LinkedIn Profile</a>  
theme: jekyll-theme-minimal
google_analytics: G-YDN7BREB7H # your Google Analytics tracking ID here
